name: check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        shell: bash
        env:
          TOKEN: ${{github.token}}
        run: |
          npm i
          npm run check
